### ISSUE TITLE
api.FileSystemSyncAccessHandle.read/write - Chromium-based browsers do not allow passing an `ArrayBuffer`

### ISSUE THREAD

**Issue by harrisi** [mdn/browser-compat-data#20745]
### What type of issue is this?

Incorrect support data (example: Chrome says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Chromium-based browsers [only accept `ArrayBufferView`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/file_system_access/file_system_sync_access_handle.h;l=51) as the first parameter to both `FileSystemSyncAccessHandle.read` and `FileSystemSyncAccessHandle.write`, whereas the [spec](https://fs.spec.whatwg.org/#api-filesystemsyncaccesshandle) says an `ArrayBuffer` should be accepted (https://webidl.spec.whatwg.org/#AllowSharedBufferSource).

### What browsers does this problem apply to, if applicable?

Chromium (Chrome, Edge 79+, Opera, Samsung Internet)

### What did you expect to see?

A note on Chromium browsers that they don't implement the spec fully.

### Did you test this? If so, how?

Yes, I have a site that was trying to write an `ArrayBuffer` that failed in Chromium-based browsers.

### Do you have anything more you want to share?

While the issue is linked only to `FileSystemSyncAccessHandle.write`, `.read` is also not fully implemented, as can be seen in the source. I have not yet opened in issue for Chromium.

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/FileSystemSyncAccessHandle/write

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.FileSystemSyncAccessHandle.write`
* Report started: 2023-09-18T22:36:11.122Z

</details>

**Comment by harrisi** [comment]
This issue was fixed in Chromium yesterday, so it should land soon. For previous versions, it would still be nice to have this specified.

https://bugs.chromium.org/p/chromium/issues/detail?id=1418593

**Comment by CameronD73** [comment]
bug still present in chrome V118, so it will be at least next month before it appears.
