### ISSUE TITLE
api.AudioParam.linearRampToValueAtTime - works fine on Firefox, but listed as non-working

### ISSUE THREAD

**Issue by parasti** [mdn/browser-compat-data#25748]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

Been using linearRampToValueAtTime for a while on Firefox without issue, so I was surprised to see that the compatibility table says "Does not work".

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Updated Firefox compatibility data.

### Did you test this? If so, how?

We use it to fade background music in the game https://play.neverball.org (30MB automatic download, sorry)

You can also try it here https://mdn.github.io/webaudio-examples/audio-param/

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/linearRampToValueAtTime

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `api.AudioParam.linearRampToValueAtTime`
* Report started: 2025-01-23T07:28:27.206Z

</details>

**Comment by caugner** [comment]
@parasti Good catch, thank you, this was indeed fixed in Firefox 134 via https://bugzilla.mozilla.org/show_bug.cgi?id=1308435.

Would you like to open a PR to update the support data by adding `version_removed: "134"` to the current statement, making it an array, and adding a new statement with `version_added: "134"` without partial_implementation here:

https://github.com/mdn/browser-compat-data/blob/182193b8fe44bdd56e362c194cfd19898f2c1a12/api/AudioParam.json#L276-L280

(If you do, you could make the existing note a bit clearer. If I understand the issue correctly, the method `linearRampToValueAtTime()` existed, but it set the `value` without transition, is that it?)

**Comment by s0rent** [comment]
@caugner 
The "RampToValue" functions still don't work in Firefox. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1567777

- Open https://mdn.github.io/webaudio-examples/audio-param/
- Press play
- Press "Linear ramp gain to 0 in 2 seconds"
- Wait for the volume to go down
- Press "Linear ramp gain to 1 in 2 seconds"

Expected result: Should ramp volume up gradually
Actual result: Instantly sets volume to 1

It is not only this particular combination of steps that are not working. For the past several years, the feature has been in different states of broken.
