### ISSUE TITLE
javascript.builtins.FinalizationRegistry.register - Non-registered symbol as target supported in Firefox 144

### ISSUE THREAD

**Issue by mvduin** [mdn/browser-compat-data#28521]
### What type of issue is this?

Incorrect support data (example: BrowserX says "86" but support was added in "40")

### What information was incorrect, unhelpful, or incomplete?

The "Non-registered symbol as target" feature for FinalizationRegistry.register is listed as not supported in Firefox.

### What browsers does this problem apply to, if applicable?

Firefox

### What did you expect to see?

Supported in Firefox 144

### Did you test this? If so, how?

I did not test it, I trust the linked bug report which indicates it has been fixed.

### Can you link to any release notes, bugs, pull requests, or MDN pages related to this?

https://bugzilla.mozilla.org/show_bug.cgi?id=1863140

### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/register

### MDN metadata

<details>
<summary>MDN page report details</summary>

* Query: `javascript.builtins.FinalizationRegistry.register`
* Report started: 2025-11-24T18:57:05.686Z

</details>

**Comment by caugner** [comment]
Resolved via https://github.com/mdn/browser-compat-data/pull/28576.

(We run semi-automated collector runs on beta versions, which usually update this data.)

**Comment by mvduin** [comment]
The same issue is still present for the unregister method:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/unregister#browser_compatibility

**Comment by caugner** [comment]
> The same issue is still present for the unregister method:
> 
> [developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/unregister#browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry/unregister#browser_compatibility)

The explanation is that there is no collector test for this aspect on the `unregister()` method, see: https://github.com/search?q=repo%3Aopenwebdocs%2Fmdn-bcd-collector+%2Fsymbol_as_target%2F&type=code

Are you able to open a PR on the BCD collector repo adding this custom test?

**Comment by mvduin** [comment]
> Are you able to open a PR on the BCD collector repo adding this custom test?

Done: https://github.com/openwebdocs/mdn-bcd-collector/pull/3368
