### ISSUE TITLE
`let` needs implementation notes for IE

### ISSUE THREAD

**Issue by tjcrowder** [mdn/browser-compat-data#3198]
`javascript/statements.json` lists that IE11+ supports `let`. It does have a `let` keyword, but the semantics are not correct per ES2015, in a way with major real-world consequences:

```js
for (let i = 0; i < 3; ++i) {
    setTimeout(function() {
        console.log(i);
    }, 0);
}
```

On IE, that outputs `3` `3` `3`, where by ES2015 semantics it should output `0` `1` `2` (addressing the closures in loops problem). https://jsbin.com/goqiheleru/

I'll fix it and do a PR.

**Comment by vinyldarkscratch** [comment]
Hey @tjcrowder, do you plan on following up on this?

**Comment by tjcrowder** [comment]
@vincent-dm - Great timing, just noticed this on my"to do" bookmarks again yesterday. Hyper-hammered with work right now but might be able to get to it in a week or two. It's probably a five-minute job for someone who knows the files, but I'm new. :-)

**Comment by vinyldarkscratch** [comment]
Haha, you're all good, I totally understand!  Please, take all the time you need, and just holler at one of us if you ever need assistance.  :wink:

_(P.S. you might have mentioned the wrong person!)_

**Comment by vinyldarkscratch** [comment]
So after further review, it looks like it basically acts like `var` in IE 11 and Edge 12+13.  Changing `let` to `var` in that example and running it in Chrome yielded the same results.  Edge 14 does not have this issue.  Thanks for reporting this issue!

I'll go ahead and write up a PR for this.  :wink:

**Comment by tjcrowder** [comment]
@vinyldarkscratch - In IE11 (I don't know about Edge 11-13), it's more like `let` than `var` **other than** it doesn't have the correct behavior in `for` loops. For instance, this logs "1:inner" and then "2:outer" as it should (but wouldn't if it were `var`):

```js
let a = "outer";
{
    // log(0 + ":" + a);
    let a = "inner";
    log(1 + ":" + a);
    // let a = "inner2";
}
log(2 + ":" + a);
```
And if you un-comment-out the `log(0 + ":" + a);` line, it correctly complains about the TDZ ("SCRIPT5113: Use before declaration"). If you leave that line commented out but un-comment-out the `let a = "inner2";` line, it correctly complains about the redeclaration ("SCRIPT1052: Let/Const redeclaration").

So really it's just the `for` case where it's incorrect, I think.

**Comment by vinyldarkscratch** [comment]
Ah, gotcha -- I just updated my PR.  Does the updated note seem appropriate?

**Comment by tjcrowder** [comment]
@vinyldarkscratch It still doesn't behave like `var` (function scope). I think I'd go with something like:

> In (X), <code>let</code> within a <code>for</code> loop initializer does not create a separate variable for each loop iteration as defined by ES2015. Instead, it behaves as though the loop were wrapped in a scoping block with the <code>let</code> immediately *before* the loop.

Separately, is it just Edge 12 and 13? What about 11 and earlier?

How are you testing old versions of Edge? VMs from MS or...? Thanks.

**Comment by vinyldarkscratch** [comment]
I like your wording much better, thank you!  I’ll update the PR accordingly.  😉

As for Edge versions, to give some context, Edge is a direct continuation off of Internet Explorer.  Our data keeps the two separate as per an MDN-wide decision (mostly because Microsoft refers to them separately).

I’m testing Edge via SauceLabs.  I tested Edge 13 and 14, and found that 14 behaved normally, but 13 did not.

**Comment by tjcrowder** [comment]
@vinyldarkscratch Oh now I should have known that. So the sequence is IE10, IE11, Edge 12, Edge 13... Thanks!
