### ISSUE TITLE
SpeechSynthesis resume() and pause()

### ISSUE THREAD

**Issue by lanzosuarez** [mdn/browser-compat-data#4500]
SpeechSynthesis resume() and pause() doesn't seem to work correctly in Chrome for Android.

Pausing, just causes the current utterance to end, so calling resume is a no op.

Works properly on a desktop browser though

Environment: Version 75.0.3770.142

**Comment by lanzosuarez** [comment]
Same behavior with Firefox mobile

**Comment by Elchi3** [comment]
Fixed in https://github.com/mdn/browser-compat-data/pull/4733

**Comment by Zaffer** [comment]
Not solved yet. See here: 
https://stackoverflow.com/questions/58953882/resuming-a-paused-speech-using-speechsynthesis-resume-on-chrome-android-doesn

**Comment by ahmedmansoor** [comment]
Not solved yet. Still facing this issue in Android Chrome.

**Comment by itzmidinesh** [comment]
Not solved yet. The issue is still happening in Chrome on Android. Works perfectly with Chrome on Windows though. Is there a fix in the works?

**Comment by Elchi3** [comment]
Please refer to the chromium bug tracker https://bugs.chromium.org/p/chromium/issues/list?q=SpeechSynthesis%20pause&can=2

This repo is about recording compatibility information.

**Comment by waldenn** [comment]
> Please refer to the chromium bug tracker https://bugs.chromium.org/p/chromium/issues/list?q=SpeechSynthesis%20pause&can=2
> 
> This repo is about recording compatibility information.

Pause() still does not work in Firefox v123! This issue is still open and the MDN page should not indicate "Firefox" support until that is the case.

**Comment by neeraj-tangariya** [comment]
pause() method is not working in mozilla app
and resume() is not working in chrome app

**Comment by dawngsang** [comment]
It works fine on safari and chrome ios but not on chrome android

**Comment by neeraj-tangariya** [comment]
> It works fine on safari and chrome ios but not on chrome android. Probably the problem of the operating system

yes speech synthesis causing issues in mobile devices not properly working.

**Comment by Alynva** [comment]
Still happening
