### ISSUE TITLE
SourceBuffer.audioTracks/videoTracks/textTracks are not actually supported

### ISSUE THREAD

**Issue by saschanaz** [mdn/browser-compat-data#5781]
[BCD says it's supported for all browsers for a long time](https://developer.mozilla.org/en-US/docs/Web/API/SourceBuffer/audioTracks) but actually both Firefox and Chrome does not have them.

**Comment by saschanaz** [comment]
* Firefox never supported them https://searchfox.org/mozilla-central/source/dom/webidl/SourceBuffer.webidl
* Chrome added flagged support for audioTracks/videoTracks in [March 2016](https://chromium.googlesource.com/chromium/src/+/92333c0e5ca6b7768e5bcf6d41ff8fc733ebbfc1), but no textTracks
* Safari added support for all of them in [January 2015](https://trac.webkit.org/changeset/178172/webkit)

**Comment by sideshowbarker** [comment]
I’m closing this issue as being fixed by #5828. I’m aware of the comment there which says:

> This only removes unsupported features without fixing version numbers for supported ones

…but *“fixing version numbers for supported ones”* can be handled by another PR or issue.

**Comment by foolip** [comment]
https://github.com/mdn/browser-compat-data/pull/5828 only partially fixed this, the support data for audioTracks/videoTracks is still wrong for at least Chrome.

**Comment by saschanaz** [comment]
Ah, I opened #6102 for that.

**Comment by sideshowbarker** [comment]
It seems like we could really use some guidance and insight from @jpmedley on this one.

**Comment by foolip** [comment]
I've looked up where these things were implemented and sent https://github.com/mdn/browser-compat-data/pull/6655 to sort it out.

Rant: I kinda wish we didn't have flags in BCD, it's *a lot* of work to sort out when it's wrong.
