### ISSUE TITLE
Issue with "Intl.NumberFormat() constructor": currencyDisplay 'narrowSymbol' throw an error on Safari

### ISSUE THREAD

**Issue by pmrotule** [mdn/browser-compat-data#8985]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat

#### What information was incorrect, unhelpful, or incomplete?

We recently added the option `currencyDisplay: 'narrowSymbol'` in our code and as soon as it went live, we had a big wave of errors coming in from Safari users.

Basically, our prices got removed all over our site because Safari was throwing the following error:

```
currencyDisplay must be either "code", "symbol", or "name"
```

See also: https://stackoverflow.com/a/64473216/1895428

#### Specific section or headline?

Browser compatibility

#### What did you expect to see?

I would expect to see under "Browser compatibility" that Safari doesn't support `currencyDisplay: 'narrowSymbol'`

#### Did you test this? If so, how?

I tested it on Safari. It seems to also happen on any browser running on iOS.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat/NumberFormat
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/javascript/reference/global_objects/intl/numberformat/numberformat/index.html
* Last commit: https://github.com/mdn/content/commit/2d423bd1a98b85b8584f08990792ebf39fcea56b
* Document last modified: 2021-01-09T13:41:23.000Z

</details>

**Comment by ddbeck** [comment]
Thanks for reporting this!

To fix this is a bit complex. To address the specific problem of `narrowSymbol`:

1. We need a new subfeature of `javascript.builtins.Intl.NumberFormat.NumberFormat` for `currencyDisplay_option` (see [`NumberFormat.json`](https://github.com/mdn/browser-compat-data/blob/5c9fce3086e91e9994ce8e8b37791c34512718e9/javascript/builtins/intl/NumberFormat.json)).
2. We need to populate that subfeature with versions for (at least) Safari.
3. We need a note on that support statement saying that Safari throws the error for the `narrowSymbol` value and, probably, a `partial_implementation` flag.

More comprehensively—perhaps as follow up issues to this one—we ought to have a complete set of option subfeatures for `Intl.NumberFormat()`.

I'd welcome one or more PRs working on this issue!

**Comment by jculver050** [comment]
Stop

**Comment by jculver050** [comment]
Close

**Comment by vinyldarkscratch** [comment]
Looks like this was resolved by #10129!

**Comment by ddbeck** [comment]
@vinyldarkscratch Could you elaborate a bit? I listed a number of fixes that would need to be made, but I'm not sure how the 14.1 data applies. I'm not saying it's not resolved, but it's different than what I've suggested and I'd like to understand better how that happened.

**Comment by vinyldarkscratch** [comment]
My apologies, I probably got a bit overzealous on this one and didn't read through carefully, haha!

**Comment by queengooborg** [comment]
Sorry it took so long to respond.  This was actually resolved by #9371, which also closed #9319, a duplicate issue describing the same situation.  #9371 added the suggested subfeature and populated its data, adding a note describing the lack of `narrowSymbol` support in Safari.  #10129 followed up to indicate that support has now been added in Safari 14.1.
